version: '3.3'
 
services:
  funda_app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: funda_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    ports:
      - "8081:3000"